name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 #latest version of http package as of 6/10/2024
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_dotenv: ^5.1.0 #need for .env file
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_fonts: ^6.1.0
  url_launcher: ^6.3.0
  profanity_filter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
